/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    Answer: typeof import('./src/components/Dialog/Answer/index.vue')['default']
    AutoAnimateTest: typeof import('./src/components/AutoAnimateTest.vue')['default']
    Avatar: typeof import('./src/components/Avatar.vue')['default']
    copy: typeof import('./src/components/GuoguanModal copy.vue')['default']
    CountDown: typeof import('./src/components/CountDown.vue')['default']
    DaojuModal: typeof import('./src/components/DaojuModal.vue')['default']
    Excalidraw: typeof import('./src/components/Excalidraw.vue')['default']
    GuoguanModal: typeof import('./src/components/GuoguanModal.vue')['default']
    HomeBottom: typeof import('./src/components/HomeBottom/index.vue')['default']
    HomeMiddle: typeof import('./src/components/HomeMiddle/index.vue')['default']
    HomeTop: typeof import('./src/components/HomeTop/index.vue')['default']
    Loading: typeof import('./src/components/Dialog/Answer/Loading.vue')['default']
    MessagePopup: typeof import('./src/components/Common/MessagePopup.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    Model: typeof import('./src/components/HomeMiddle/Model.vue')['default']
    Placeholder: typeof import('./src/components/Dialog/Question/Placeholder.vue')['default']
    Progress: typeof import('./src/components/Progress.vue')['default']
    Question: typeof import('./src/components/Dialog/Question/index.vue')['default']
    RankItem: typeof import('./src/components/RankItem.vue')['default']
    RankModal: typeof import('./src/components/RankModal.vue')['default']
    Recorder: typeof import('./src/components/Dialog/Recorder/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SoundTest: typeof import('./src/components/SoundTest.vue')['default']
    Template: typeof import('./src/components/template.vue')['default']
    TextArea: typeof import('./src/components/Dialog/Question/TextArea.vue')['default']
  }
}
