/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AutoAnimateTest: typeof import('./src/components/AutoAnimateTest.vue')['default']
    Avatar: typeof import('./src/components/Avatar.vue')['default']
    Back: typeof import('./src/components/PlayUI/Back/index.vue')['default']
    Box: typeof import('./src/components/PlayUI/Box/index.vue')['default']
    CountDown: typeof import('./src/components/CountDown.vue')['default']
    DaojuModal: typeof import('./src/components/DaojuModal.vue')['default']
    Excalidraw: typeof import('./src/components/Excalidraw.vue')['default']
    GuoguanModal: typeof import('./src/components/GuoguanModal.vue')['default']
    House: typeof import('./src/components/PlayUI/House/index.vue')['default']
    PlayArea: typeof import('./src/components/PlayUI/PlayArea/index.vue')['default']
    Players: typeof import('./src/components/Players.vue')['default']
    PlayUI: typeof import('./src/components/PlayUI/index.vue')['default']
    Prompt: typeof import('./src/components/PlayUI/Prompt/index.vue')['default']
    RankItem: typeof import('./src/components/RankItem.vue')['default']
    RankModal: typeof import('./src/components/RankModal.vue')['default']
    Road: typeof import('./src/components/PlayUI/Road/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SoundTest: typeof import('./src/components/SoundTest.vue')['default']
    Template: typeof import('./src/components/template.vue')['default']
    Toolbox: typeof import('./src/components/PlayUI/Toolbox/index.vue')['default']
    ToolItem: typeof import('./src/components/PlayUI/Toolbox/toolItem.vue')['default']
  }
}
